servers:
  - url: http://host.docker.internal:8000

openapi: 3.0.1
info: { title: PriceFeed API, version: "1.0.0" }
paths:
  /prices/latest:
    get:
      summary: Get indicative prices for a commodity and region from CSV
      parameters:
        - in: query
          name: commodity
          schema: { type: string, example: "cassava_tuber" }
        - in: query
          name: market
          schema: { type: string, example: "Ibadan" }
      responses:
        "200":
          description: Price band
          content:
            application/json:
              schema:
                type: object
                properties:
                  currency: { type: string }
                  min_price: { type: number }
                  max_price: { type: number }
                  avg_price: { type: number }
                  week_ending: { type: string, format: date }
